#!/bin/sh

### BEGIN INIT INFO
# Provides:       rtorrent
# Required-Start:  $network $local_fs $remote_fs
# Required-Stop:   $network $local_fs $remote_fs
# Default-Start:   2 3 4 5
# Default-Stop:    0 1 6
# Short-Description: Start rtorrent as a daemon
### END INIT INFO

#Do not put a space on either side of the equal signs e.g.
# user = user # will not work
user="pi"

# the full path to the filename where you store your rtorrent configuration
config="/home/${user}/.rtorrent.rc"

# name of dtach session
session="/home/${user}/.rtsession"
socket="${session}/rtorrent.dtach"

DESC="rtorrent"
NAME=rtorrent
DAEMON=/usr/bin/dtach
RTORRENT=/usr/bin/rtorrent
SCRIPTNAME=/etc/init.d/$NAME
PID_FILE=$session/rtorrent.pid
DAEMON_OPTS=" -n $socket $RTORRENT"

test -x $DAEMON || echo "Daemon $DAEMON not found"
test -x $RTORRENT || echo "Daemon $RTORRENT not found"

set -e

if ! [ -r "${config}" ] ; then 
    echo "Cannot find readable config in ${config}, check that permissions are appropiate."
    exit 1
fi

if ! [ -d "${session}" ] ; then
    echo "Cannot find readable session directory ${session}. Check permissions."
    exit 1
fi

if [ -e $PID_FILE ]; then
    PID=`cat $PID_FILE`
    if ! kill -0 $PID > /dev/null 2>&1; then
        echo "Removing stale $PID_FILE"
        rm $PID_FILE
    fi
fi

case "$1" in
  start)
        echo -n "Starting $DESC: $NAME"
        start-stop-daemon -c $user --start --pidfile $PID_FILE --exec $DAEMON -- $DAEMON_OPTS
        rtpid=`ps -u pi | grep rtorrent | awk '{print($1)}'`
        echo $rtpid > $PID_FILE
        ;;
  stop)
        echo -n "Stopping $DESC: $NAME"
        start-stop-daemon --stop --pidfile $PID_FILE --retry 15
        rm -f "$PID_FILE"
        ;;
  restart|force-reload)
        echo -n "Restarting $DESC: $NAME"
        start-stop-daemon --stop --pidfile $PID_FILE --retry 15
        rm -f "$PID_FILE"
        start-stop-daemon -c $user --start --pidfile $PID_FILE --exec $DAEMON -- $DAEMON_OPTS
        rtpid=`ps -u pi | grep rtorrent | awk '{print($1)}'`
        echo $rtpid > $PID_FILE
        ;;
  *)
        echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload}" >&2
        exit 1
        ;;
esac

exit 0
